name: darbah_qadiyah
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  confetti: 0.8.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  go_router: ^16.2.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/comic_style_punch_impact_explosion_without_text_transparent_1779745634987.png
    - assets/images/shattered_glass_burst_icon_without_text_transparent_1779745636380.png
    - assets/images/cracked_stone_smash_impact_icon_without_text_transparent_1779745637078.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
